const CERT = [
    '-----BEGIN CERTIFICATE-----',
    'MIIBjzCCATSgAwIBAgIUWzmEW4F3GxiU1obUU/gtb9Iz+2IwCgYIKoZIzj0EAwIw',
    'FDESMBAGA1UEAwwJMTI3LjAuMC4xMB4XDTI2MTAxMDIxMjI0NloXDTM2MTAwNzIx',
    'MjI0NlowFDESMBAGA1UEAwwJMTI3LjAuMC4xMFkwEwYHKoZIzj0CAQYIKoZIzj0D',
    'AQcDQgAEy5pAcS1gwwy7Fnso9EPPIV4SfVQXe10NZZ4B9/7NQBHW8+6LubA81YPU',
    'Ena0waJtkcl7rBj8CE2uQMMVgEhS4qNkMGIwHQYDVR0OBBYEFBmHv6GpewocEYNz',
    'dHInO89ZzICvMB8GA1UdIwQYMBaAFBmHv6GpewocEYNzdHInO89ZzICvMA8GA1Ud',
    'EwEB/wQFMAMBAf8wDwYDVR0RBAgwBocEfwAAATAKBggqhkjOPQQDAgNJADBGAiEA',
    '9eGD1O5Ttry8AwvTFuHvUmDV9Ysz2sHeqt7OUuCzXskCIQC0heO2HSmTwfDhtwQ9',
    'EQzN83miNOyM4PQ8euvt1Ek6XQ==',
    '-----END CERTIFICATE-----',
    ''
].join('\n');

const KEY = [
    '-----BEGIN PRIVATE KEY-----',
    'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQghGaRD0P/oxZUipB9',
    'YIS+Pn2d27un0K82DGCbo520Q+WhRANCAATLmkBxLWDDDLsWeyj0Q88hXhJ9VBd7',
    'XQ1lngH3/s1AEdbz7ou5sDzVg9QSdrTBom2RyXusGPwITa5AwxWASFLi',
    '-----END PRIVATE KEY-----',
    ''
].join('\n');

module.exports = { CERT, KEY };
